version: "3"

services:
  database:
    image: postgres:12.2
    container_name: devdatabase
    volumes:
      - postgredata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: fragalysis
      POSTGRES_USER: fragalysis
      POSTGRES_DB: frag
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
  graph:
    container_name: devneo4j
    image: neo4j:3.5
    ports:
      # Comment these two out in production
      - "7474:7474"
      - "7687:7687"
    ulimits:
      nofile:
        soft: 40000
        hard: 40000
    volumes:
      - neo4jdata:/data
      - neo4jlogs:/logs
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_memory_pagecache_size=4G
  app:
    container_name: devapp
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../fragalysis-backend:/code
      - ../fragalysis-frontend:/code/frontend
      - ../.devcontainer:/code/.devcontainer
    command: sleep infinity
    environment:
      POSTGRESQL_DATABASE: frag
      POSTGRESQL_USER: fragalysis
      POSTGRESQL_PASSWORD: fragalysis
      POSTGRESQL_HOST: database
      POSTGRESQL_PORT: 5432
      DEBUG_FRAGALYSIS: "True"
      OIDC_RP_CLIENT_SECRET: "c6245428-04c7-466f-9c4f-58c340e981c2"
      SQUONK_UI_URL: https://data-manager-ui.xchem-dev.diamond.ac.uk/data-manager-ui
      SQUONK_API_URL: https://data-manager.xchem-dev.diamond.ac.uk/data-manager-api
    env_file:
      - .devcontainerenv
    ports:
      - "8080:80"
    depends_on:
      - database
      - graph

volumes:
  postgredata:
  neo4jdata:
  neo4jlogs:
